[package]
name = "hc"
version = "0.1.5"
authors = ["Andrew Burkett <burkett.andrew@gmail.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bstr = "0.2"
ureq = "2.4.0"
